Add img mapper
hermanator608/wow-soundtrack-guesser pull request #4
Opened 2024-02-16 03:34 UTC by maggiemay-afk

Added react image mapper to change game from multiple choice style questions to users selecting a map area when making a guess at what zone the soundtrack is from. Also, major cleanup of unused code, components, soundtracks, etc. and styling changes to accommodate new game play style.  

- Add images (maps) for all WoW zones
- map details / clickable areas for all zones in an images
- Use stack data type for state to handle clicking on map zones and using the "back one map" button
- Add zone name to image on mouse hover of a clickable map area
- Clean up of config files to remove livestreams and other unusable soundtracks
- Clean up of unused, commented out code
- Remove unused components (i.e., Background Image)
- Remove volume slider 
- Redo styling of home page, such as not using full-screen for YouTube videos

2024-02-16 03:41 UTC, maggiemay-afk commented
Sorry, @hermanator608 - kind of a hefty PR. Let me know if you want me to break it into a couple smaller ones. 
Thank you!

2024-02-16 17:10 UTC, hermanator608 requested changes
Great work so far! I'm running into a few issues with the deployed application - 

* The first video will not start - does not work until I just select a random zone and fail and then the next video starts playing sound as it should
* The pause, skip, restart buttons are not working


Also seeing the following console error log:
```
api.ts:209 Uncaught FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call initializeApp() first (app/no-app).
    at wt (api.ts:209:25)
    at lr (api.ts:73:49)
    at logEventClickWrapper.ts:15:21
    at logEventClickWrapper.ts:23:5
    at Object.Le (react-dom.production.min.js:54:317)
    at je (react-dom.production.min.js:54:471)
    at react-dom.production.min.js:55:35
    at Fr (react-dom.production.min.js:105:68)
    at zr (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104
```

2024-02-16 17:10 UTC, hermanator608 commented on src/App.css
> +} */
Delete this if not using?

2024-02-16 17:10 UTC, hermanator608 commented on src/App.tsx
> +function App(props: any) {
Did you have to add props here? Looks like they are not used?

2024-02-16 17:10 UTC, hermanator608 commented on src/App.tsx
> +    }
Do we really want to alert to a user if we dont have this defined?

2024-02-16 17:10 UTC, hermanator608 commented on src/App.tsx
> +  //TODO: Change from alert to something else
Should we finish this TODO? Or do you plan to update in followup PR?

2024-02-16 17:10 UTC, hermanator608 commented on src/App.tsx
> +    // if (score === 5) //TODO: End Game
Looks like we set score but dont display it anywhere?

2024-02-16 17:10 UTC, hermanator608 commented on src/config/types.ts
> +export class Stack<MapDetails> implements stackInterface<MapDetails> {
Can we move this to something like - `src/utils/MapStack.ts`?

2024-02-16 17:10 UTC, hermanator608 commented on src/config/wow/miscellaneous.ts
>      channel: channels.Meisio,
Might just want to get rid of all these "gameplay" ones at they dont focus on the music and have other distracting noises like fighting, quests pickup/turn-in, etc

2024-02-16 17:10 UTC, hermanator608 commented on src/state.ts
> +  //options: number[];
We should remove these if not used

2024-02-16 17:10 UTC, hermanator608 commented on src/state.ts
> +  //const answer = Math.floor(Math.random() * options.length);
Remove?

2024-02-16 17:10 UTC, hermanator608 commented on src/state.ts
> +    //options,
rm

2024-02-16 17:10 UTC, hermanator608 commented on src/state.ts
> +  console.log(answerName);
Probably should remove this? Otherwise users could cheat?

2024-02-16 17:10 UTC, hermanator608 commented on src/App.tsx
> +        Back One Map
Maybe we can just update this to `back`? I think it'd be better to move this button to the top left of the map image. The location for me is a bit confusing.

2024-02-16 17:10 UTC, hermanator608 commented on src/App.tsx
> +        Back One Map
Or even could just be a back arrow in the top left corner of the Map Image?

2024-02-18 18:58 UTC, maggiemay-afk commented on src/App.tsx
> +  //TODO: Change from alert to something else
Plan to update this in a follow up PR - will be adding scoring, and this would be part of the scoring functionality.

2024-02-18 18:59 UTC, maggiemay-afk commented on src/App.tsx
> +    // if (score === 5) //TODO: End Game
Removing this line as well as the state for score. Similar to comment above, will be doing a follow up PR for scoring.

2024-02-18 19:00 UTC, maggiemay-afk commented on src/App.tsx
> +    // if (score === 5) //TODO: End Game
More specifically, removing line 81, 82, and 24 in the App.tsx file

2024-02-18 19:48 UTC, maggiemay-afk commented on src/App.tsx
> +function App(props: any) {
Added this by mistake. No, don't need any props here

2024-02-18 19:52 UTC, maggiemay-afk commented
Recap of new changes: 

- Correctly initialize firebase
(this change also seemed to fix the issue with buttons not working. Buttons appear to be working now on the GitHub test URL.
- Deleted the commented out code, unused code, and logs used for testing 
- Updated the back button, overlaying this on the image now
- Removed the bits of code pertaining to scoring. Will be doing a new PR just for scoring

2024-02-18 23:32 UTC, hermanator608 requested changes

2024-02-18 23:32 UTC, hermanator608 commented on src/config/types.ts
> +export interface stackInterface<MapDetails> {
Nit: Capitalize this please

2024-02-18 23:32 UTC, hermanator608 commented on src/config/types.ts
> +export class Stack<MapDetails> implements stackInterface<MapDetails> {
Please update this too :ty:

2024-02-18 23:32 UTC, hermanator608 commented on src/config/wow/miscellaneous.ts
>      channel: channels.Meisio,
bump

2024-02-19 17:00 UTC, maggiemay-afk commented
Sorry - missed those comments you had made earlier 
Changes: 
- Remove gameplay videos from the miscellaneous.ts file
- Move the Stack class out of types.ts and into new file, src/utils/MapStack.ts
- Update StackInterface - capital

2024-02-19 20:43 UTC, hermanator608 approved these changes
LGTM great work! 🔥

2024-02-19 21:10 UTC, merged